version: 2

before:
  hooks:
    - go mod tidy
    - go vet ./...

builds:
  - main: ./cmd/smirror/
    binary: smirror
    ldflags:
      - -s -w -X main.version={{.Version}}
    env:
      - CGO_ENABLED=1
    goos:
      - windows
    goarch:
      - amd64

archives:
  - formats: ['zip']
    files:
      - README.txt
      - LICENSE
      - CREDITS.md
      - THIRD-PARTY-LICENSES.txt
      - config.example.yaml

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'

release:
  github:
    owner: qraveh
    name: SelectiveMirror
  draft: true
  prerelease: auto
